# Azure Files用 PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-files-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany  # 複数ノードからアクセス可能
  storageClassName: azurefile-csi-smb
  resources:
    requests:
      storage: 5Gi