apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myReplicaSet
  labels:
    key: value
spec:
  replicas: 3
  selector:
    matchLabels:
      key: value
  template:
    metadata:
      labels:
        key: value
    spec:
      containers:
        - name: myContainer
          image: nginx:latest
