apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wordpress-kv
spec:
  provider: azure
  parameters:
    keyvaultName: "krmt-key01"                      # 実際の Key Vault 名 (小文字)
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"
    objects: |
      array:
        - |
          objectName: mysql-root-password
          objectType: secret
        - |
          objectName: mysql-database
          objectType: secret
        - |
          objectName: mysql-user
          objectType: secret
        - |
          objectName: mysql-password
          objectType: secret
  secretObjects:
    - secretName: wordpress-db-secret-kv
      type: Opaque
      data:
        - objectName: mysql-root-password
          key: MYSQL_ROOT_PASSWORD
        - objectName: mysql-database
          key: MYSQL_DATABASE
        - objectName: mysql-user
          key: MYSQL_USER
        - objectName: mysql-password
          key: MYSQL_PASSWORD
        - objectName: mysql-user
          key: WORDPRESS_DB_USER
        - objectName: mysql-password
          key: WORDPRESS_DB_PASSWORD
        - objectName: mysql-database
          key: WORDPRESS_DB_NAME
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-app-sa
  annotations:
    azure.workload.identity/client-id: "efe93dee-b2bc-4744-a424-415b2a5141cc"